# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.5 on 2017-01-24 12:10
=======
# Generated by Django 1.10.5 on 2017-01-24 13:48
>>>>>>> df061446c8ef235667945a254571b871ad0c3668
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('imager_profile', '0003_auto_20170124_0313'),
=======
        ('imager_profile', '0003_auto_20170119_1113'),
>>>>>>> df061446c8ef235667945a254571b871ad0c3668
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='active',
        ),
    ]
